name: car_go_pfe_lp_j2ee_driver
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  audioplayers: ^6.1.0
  cloud_firestore: null
  connectivity_plus: null
  device_info_plus: null
  firebase_app_check: null
  firebase_auth: null
  firebase_core: null
  firebase_database: null
  firebase_messaging: null
  firebase_storage: null
  flutter:
    sdk: flutter
  flutter_dotenv: null
  flutter_geofire: null
  flutter_image_compress: null
  geolocator: null
  google_maps_flutter: null
  http: ^1.2.2
  image: null
  image_picker: null
  permission_handler: null
  provider: null
  shared_preferences: null
  url_launcher: null
  uuid: null

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

  assets:
    - assets/images/
    - assets/sounds/
    - themes/
    - .env
