name: car_go_pfe_lp_j2ee_driver
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: ^5.2.1
  connectivity_plus: ^6.0.5
  device_info_plus: ^10.1.2
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_database: ^11.0.4
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_geofire: ^2.0.3
  flutter_image_compress: ^2.3.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.9.0
  image: ^4.2.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

  assets:
    - assets/images/
    - assets/sounds/
    - themes/
    - .env
